### ISSUE TITLE
Font does not resize on apply / ok.

### ISSUE THREAD

**Issue by jameswintermute** [lxqt/qterminal#722]
Whilst attempting to resize font from default 10px to 13px on a 4k resolution screen the setting does not take effect. 

##### Expected Behavior

Font size takes effect and is easier to read

##### Current Behavior

Changing default font size has no effect.

##### Steps to Reproduce (for bugs)

1. Open QT
2. Select preferences from menu
3. Change font size (top menu option) from 10, to 13, attempt to apply or ok
4. result does not take effect on close or restart, remains at 10px

##### Context
Difficult to read screen in terminal, very small font size. Setting overall platform font undesirable and out of scale.

##### System Information 
* Distribution & Version:  Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
* Qt Version: 5.14.2
* qtermwidget Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by grese** [comment]
I'm having the same issue. The version is 5.4.12. In my case, I'm totally unable to change the font. I can select one from the dropdown, but it is never reflected in the terminal settings or the terminal. The same issue happens with the font size. Even if I try manually change the font in the qterminal.ini file, it gets reset to the original value whenever I start a new terminal (strange!).

Here is a screenshot that may help...
<img width="719" alt="Screen Shot 2020-11-09 at 12 34 01 AM" src="https://user-images.githubusercontent.com/4702431/98518000-a1e0dc00-2223-11eb-9ebb-0d751925c1e3.png">

**Comment by tsujan** [comment]
> The version is 5.4.12.

Doesn't exist.

**Comment by grese** [comment]
> > The version is 5.4.12.
> 
> Doesn't exist.

Maybe I'm confused then... Is there another QTerminal Project?

**Comment by grese** [comment]
> > The version is 5.4.12.
> 
> Doesn't exist.

My bad.   I see, there are multiple of version printed on the product.  One dialog box says the "QT" version which is 5.14.2.   I guess you are looking for the "QTerminal version", which is "0.14.1". 

<img width="423" alt="Screen Shot 2020-11-09 at 2 36 56 AM" src="https://user-images.githubusercontent.com/4702431/98531060-a5309380-2234-11eb-85e2-e097153739cd.png">

**Comment by jubalh** [comment]
We just released 0.16.0. 0.14.1 is from February 2019. This is not our problem I'd say.

**Comment by grese** [comment]
Ok, I'll try to find a way to update. Kali's only have 0.14.1, but I'll see if they can update it.

**Comment by jubalh** [comment]
Just use a better distro ;)

**Comment by grese** [comment]
Kali has updated the version.  I'm now using 0.16.1, and the font issue still persists.  Can you tell me where Qterminal looks for fonts?

**Comment by grese** [comment]
> Just use a better distro ;)

Or a different terminal, I guess.  This issue only seems to happen with QTerminal.

**Comment by tsujan** [comment]
> Can you tell me where Qterminal looks for fonts?

Qterminal doesn't look for fonts; Qt does. Most probably, the cause of your problem is outside Qterminal.

**Comment by tsujan** [comment]
Also, see whether the problem is really https://github.com/lxqt/qterminal/issues/779 and not what's reported here.

**Comment by grese** [comment]
@tsujan - It doesn't sound to me like #779 is the same as my issue. The font settings never get applied, but I don't notice any strange behavior with respect to the window closing.

**Comment by stefonarch** [comment]
I see it's   reproducible here (not using dropdown) with Dina for example.
Which font do you try to change?

**Comment by tsujan** [comment]
> I see it's reproducible here (not using dropdown) with Dina

I'll install Dina tonight to check how Qt handles it and whether it's different from how QTerminal does.

**Comment by tsujan** [comment]
Oh, Dina could be installed with pacman; I did and checked it with FeatherPad: It didn't have fixed-pitch (= monospace) size > 10.

FeatherPad and QTerminal both use standard Qt tools and Qt is good at checking the fixed-pitch property. Dina has a problem.

However, I can't reproduce the problem with Bitstream Vera Sans Mono. It's OK.

**Comment by grese** [comment]
@tsujan - I was able to fix my issue by deleting the config files from `/home/kali/.config`.

Now the only issue is that not all unicode characters are displayed correctly. I expect that this is due to a font mismatch. I noticed that other terminals in my system find a list of over 100 fonts, and qterminal only displays a list of about 12. Would that also be a QT issue?

**Comment by tsujan** [comment]
> and qterminal only displays a list of about 12. Would that also be a QT issue?

No, there isn't any bug. Qt correctly finds fixed-pitch fonts and QTerminal use them. A terminal emulator should only use fixed-pitch fonts.

**Comment by grese** [comment]
> > and qterminal only displays a list of about 12. Would that also be a QT issue?
> 
> No, there isn't any bug. Qt correctly finds fixed-pitch fonts and QTerminal uses them. A terminal emulator should only use fixed-pitch fonts.

Oh, good point. I just looked, and some of those fonts are not monospace. 

However, QTerminal is the only one that can't display certain unicode characters. Have a look at the screenshots below. The first screenshot is QTerminal, and the second is Xfce Terminal. Notice that in the middle of the prompt, QTerminal is missing this odd unicode character. Both terminals are using the "Monospace" font. I also checked other terminals (e.g. Terminator, Tilex, etc), and they all display that character correctly. Apologies if this is a noob question. I'm not all that familiar with how to deal with font issues in terminals.

**QTerminal**
![Qterminal prompt](https://i.ibb.co/zSV4Nsv/Screen-Shot-2021-01-04-at-7-32-23-PM.png)


**Xfce Terminal**
![Xfce prompt](https://i.ibb.co/jH8LMpX/Screen-Shot-2021-01-04-at-7-31-58-PM.png)

**Comment by tsujan** [comment]
I have no idea what may be wrong with your font settings but this is QTerminal with the characters you mentioned -- and more:

![unicode](https://user-images.githubusercontent.com/981076/103621002-c3232780-4f49-11eb-9b9d-68b0a18a5482.png)

**Comment by tsujan** [comment]
> Both terminals are using the "Monospace" font.

"monospace" is an alias that's mapped to certain fonts. If those fonts aren't good enough, they might not show some characters correctly.

I use "DejaVu Sans Mono" as the preferred "monospace" and "Noto Color Emoji" for colored emojis, having added these lines to `~/.config/fontconfig/fonts.conf`:
 
```xml
 <!-- For colored emojis: -->
 <match target="pattern">
  <test name="family">
   <string>monospace</string>
  </test>
  <edit mode="append" name="family">
   <string>Noto Color Emoji</string>
  </edit>
 </match>
 <!-- Preferred monospace: -->
 <alias>
  <family>monospace</family>
  <prefer>
   <family>DejaVu Sans Mono</family>
  </prefer>
 </alias>
```

**Comment by grese** [comment]
> > Both terminals are using the "Monospace" font.
> 
> "monospace" is an alias that's mapped to certain fonts. If those fonts aren't good enough, they might not show some characters correctly.
> 
> I use "DejaVu Sans Mono" as the preferred "monospace" and "Noto Color Emoji" for colored emojis, having added these lines to `~/.config/fontconfig/fonts.conf`:
> 
> ```
>  
>  <match target="pattern">
>   <test name="family">
>    <string>monospace</string>
>   </test>
>   <edit mode="append" name="family">
>    <string>Noto Color Emoji</string>
>   </edit>
>  </match>
>  
>  <alias>
>   <family>monospace</family>
>   <prefer>
>    <family>DejaVu Sans Mono</family>
>   </prefer>
>  </alias>
> ```

@tsujan 
I was able to see those fonts (DejaVu Sans Mono and Noto Color Emoji) show up in my font list, so as a sanity check, I gave them a try.

First, I tried Noto Color Emoji, and it loaded, but didn't display those unicode chars. 

Then, I tried "DejaVu Sans Mono", but it doesn't even look like that font loaded because the font displayed in qterminal was not sans-serif. It appears to be falling back to some other font.

You mentioned previously that before that QT is responsible for locating the fonts, so maybe I I'll try to check with them to see how they're doing it.

**Comment by tsujan** [comment]
> so maybe I I'll try to check with them to see how they're doing it.

Qt just uses `fontconfig`, which is the Freedesktop [standard](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html).

Your monospace (which can be known from `fc-match monospace`) doesn't support many emoji characters. To show emojis correctly in all Qt apps that use Monospace (not just QTerminal), there are various ways. The easiest way is what I mentioned above. To make it still easier:

If you have "Noto Color Emoji", create `~/.config/fontconfig/conf.d/0-emoji.conf` with these lines in it:
```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<!-- created by lxqt-config-appearance (DO NOT EDIT!) -->
<fontconfig>
 <!-- For colored emojis: -->
 <match target="pattern">
  <test name="family">
   <string>monospace</string>
  </test>
  <edit mode="append" name="family">
   <string>Noto Color Emoji</string>
  </edit>
 </match>
</fontconfig>
```
Then, just restart any Qt app that uses Monospace (lo logout/login is needed).

You could also replace "Noto Color Emoji" with another font that supports a rich set of emojis.

**Comment by daniruiz** [comment]
The original issue was the same as this one: https://github.com/lxqt/qterminal/issues/708 terminal does not properly change the font if the current one is no longer installed. In this case, the font in use was 'Fira Code', which was working before, but at some point an update from qt made it break with that name, and was only fixed after removing the space from the name (usually fonts have spaces in their name, the issue is not about the font being misspelled).

The other issue, about the emojis and other special characters, happens after fonts-noto-core gets installed (mainly as a dependency of libreoffice), this happens also on konsole, so it might be an issue of configuring monospace fonts for qt apps, but it would be really helpful if you could point out where to start looking for fixing it :wink: 
Removing fonts-noto-core fixes the issue
