### ISSUE TITLE
Drop-down global shortcut with key unmaped in keyboard layout breaks X11 input

### ISSUE THREAD

**Issue by leogama** [lxqt/qterminal#794]
Setting the global shortcut to a (valid) key that isn't mapped to any physical key in the current keyboard layout (ex.: `F13`) makes the drop-down QTerminal capture all keys from all X11 windows(!).

Additionally, it seems that if the shortcut is set to an invalid value (ex.: "Spam") using the settings dialog, instead of causing an error, the shortcut is actually set to the `Delete` key.

**Note:** I'm using version 0.14.1 on Ubuntu 20.04, but it seems that [the code responsible for this function](https://github.com/lxqt/qterminal/blob/master/src/third-party/qxtglobalshortcut_x11.cpp) is pretty much unmodified in the last years.

##### Expected Behavior

For the valid but unmapped key case, the shortcut would not work, of course. But QTerminal should not consume the keypresses.

For the invalid key case, it should show an error message on clicking "Apply" or "OK", don't register the shortcut and either undo the setting or clear the shortcut.

##### Steps to Reproduce (for bugs)

1. Launch QTerminal in drop-down mode
2. Open `Preferences` > `Dropdown` > `Shortcut`
3. Set the global shortcut to a valid key that doesn't exist in the current keyboard layout (ex.: `F13`) and apply
4. Close the preferences dialog and try to type text in the terminal or any other program's window (it shouldn't work)
5. Open a "system monitor" using the mouse and kill the `qterminal` process (keyboard should start working again)
6. Map some key to the problematic key used in step (3) with `xmodmap`:
    `$ xmodmap -e 'keysym Escape = F13'`
7. Repeat the steps (1) to (4) and verify that the buggy behavior disappeared

##### Context

I hit this problem after upgrading my system. I have modified the layout file for the keyboard layout that I use to remap the `Caps Lock` key to `Escape` and the `Escape` key to `F13`, so that I could use it exclusively as a drop-down terminal shortcut. The upgrade overwrote the layout file and undid my modifications. I had QTerminal dropdown set as an startup app and, suddenly, when I logged in the first time after the upgrade, my keyboard didn't work anymore! It took me a couple days of tracking down to figure out that QTerminal was to blame, but at least it was easy to fix the problem.

##### System Information

* Distribution & Version: Ubuntu 20.04 amd64
* Kernel: 5.4.0-65-generic
* Qt Version: 5.12.8
* qtermwidget Version: 0.14.1-3ubuntu1
* lxqt-build-tools Version: does not apply
* Package version: 0.14.1-0ubuntu2

**Comment by stefonarch** [comment]
From point 4) with F14 I cannot reproduce - I can write everywhere.

**Comment by tsujan** [comment]
Not reproducible here either.

Anyway, 0.14 is very old.

> But there's another issue I think, ...

That's not an issue. If you had an instance of QTerminal *before* changing the shortcut to F14, the change won't be reflected by it because QTerminal isn't a single-instance app. But if you open an instance of QTerminal *after* changing the shortcut, it'll be reflected by it.

**Comment by leogama** [comment]
I was able to reproduce this on a different machine with the same Ubuntu version.

Given the nature of the buggy behaviour, I'm suspecting this is a problem in an older version of X11 libs (or Gnome?) that ship with Ubuntu 20.04. I'll take this bug report over there.

**Thank you for your time!** :fist_oncoming:

**Comment by tsujan** [comment]
The settings GUI shouldn't accept an impossible shortcut and that's a problem that should be fixed but, as @stefonarch and I checked, `F13` and `F14` didn't cause any problem in other apps or in QTerminal.

If you see the problem with the latest version of QTerminal, please tell us.

**Comment by wxl** [comment]
@leogama you can use [this PPA](https://launchpad.net/~lubuntu-ci/+archive/ubuntu/unstable-ci?field.series_filter=focal) to install the latest with ease. If it's still problematic, yeah, it's probably something outside of QTerminal.

It might also be a good idea to check out 20.10 (or a daily of Hirsute) and see if it's similarly problematic. I guess if that solves the problem perhaps the simple route here is to just install a newer version, which will benefit you overall.

**Comment by leogama** [comment]
Thank you for the tip @wxl! I had no luck with the PPA you linked because the `libqtermwidget` packages' version doesn't match the `qterminal` packages' one, but found [this another PPA](https://launchpad.net/~lubuntu-ci/+archive/ubuntu/stable-backports-ci) from the same team with matching versions.

Indeed, the problem persists, but setting the keyboard layout again will fix it. At least I've got a newer version of QTerminal. :smile:

**Comment by wxl** [comment]
@leogama that other PPA is just the most recent packages in the Lubuntu repos though it should be equivalent to what is in the archives. In neither case are these tested or supported so if they screw everything up, you've only got yourself to blame. 

That said, the original PPA I mentioned has the same version from what I can tell and is the only one that will test `git` master, the whole reason I brought it up.
